### ISSUE TITLE
Using commas for floating numbers in the budget screen

### ISSUE THREAD

**Issue by 0xClpz** [hwaterke/inab#2]
In some areas of the applications we can use both a comma or a dot to represent a floating number but using a comma in the budget screen crashes the app.

Steps to reproduce:
- Open the budget screen
- Double click "budgeted" on a category
- Update the number with a floating number using a comma instead of a dot

Error reported on the client "Error: update - SQLite3::ConstraintException: NOT NULL constraint failed: budget_items.amount"

**Comment by hwaterke** [comment]
Indeed.

The budget table uses input of type text while the transaction screen uses input of type number. This needs to be fixed. I'll have a look as soon as possible !

**Comment by hwaterke** [comment]
Fixed and pushed to docker.
You can pull the new image for the fix.
(always make a backup of your database before upgrading)

Don't hesitate to create more issues!
